name: Dart CI

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main]

jobs:
  dart-package-test:
    name: Dart Package Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Set up Dart
        uses: dart-lang/setup-dart@v1
        with:
          sdk: stable

      - name: Prevent example from resolving Flutter dependencies
        run: rm -rf example

      - name: Install Dependencies
        run: dart pub get

      - name: Analyze Code
        run: dart analyze

      - name: Run Tests
        run: dart test

  flutter-example-test:
    name: Flutter Example Checks
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set Up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          flutter-version: "3.29.1"
          cache: true

      - name: Validate Example App
        working-directory: example
        run: |
          flutter pub get
